name: dev-deplyment
on:
  push:
    branches:
      - main
    paths:
      - 'backend-api/src/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./backend-api
        run: npm install --force
      - name: Build
        working-directory: ./backend-api
        run: npm run build

        # transfer build to ec2 server by scp except node_modules and src
      - name: Deploy build to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'backend-api/dist,backend-api/package*.json'
          target: '~/backend-api'
          strip_components: 1

      # setup nodejs and install dependencies on ec2 server
      - name: Ensure target directory exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd backend-api
            npm install
